micronaut:
  application:
    name: lambda-manager
  server:
    port: 30009
    maxRequestSize: 100MB
    max-request-size: 100MB
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: true
    cors:
      enabled: true
  minio-url: http://localhost
  minio-port: 9000
  minio-server: minio-storage
  minio-user: ROOTNAME
  minio-password: CHANGEME123
